language: ruby
rvm:
  - 1.9.2
  - 1.9.3
  - jruby-19mode # JRuby in 1.9 mode
  - rbx-19mode

  cd test/dummy/ && rake db:create db:migrate db:test:prepare

before_script:
  - cd test/dummy/ && rake db:create db:migrate db:test:prepare
